ped_api:
    host: "%api_server_host"
    type: "%api_type%"
    client:
        id: "%api_client_id%"
        secret: "%api_client_secret%"

fos_oauth_server:
    db_driver:           orm
    client_class:        PaneeDesign\ApiBundle\Entity\Client
    access_token_class:  PaneeDesign\ApiBundle\Entity\AccessToken
    refresh_token_class: PaneeDesign\ApiBundle\Entity\RefreshToken
    auth_code_class:     PaneeDesign\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
        templating_formats:
            html: true
        force_redirects:
            json: true
        view_response_listener: force
    routing_loader:
        default_format: json
        include_format: false #temp disable to have api/doc more readable
    serializer:
        serialize_null: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    param_fetcher_listener: force
    allowed_methods_listener: true
    disable_csrf_role: ROLE_API
    access_denied_listener:
        json: true