parameters:
    ped_api.access_token_manager.class: PaneeDesign\ApiBundle\Manager\TokenManager
    ped_api.client.class:               PaneeDesign\ApiBundle\OAuth2\Client
    ped_api.api_key_grant.class:        PaneeDesign\ApiBundle\OAuth2\ApiKeyGrantExtension
    ped_api.oauth2_user_entity.class:   '%api_user_class%'
    ped_api.oauth2_client.class:        OAuth2\Client
    ped_api.oauth.grant_url:            '%api_server_host%/oauth/v2/api_key'
    ped_api.oauth.token_url:            '%api_server_host%/oauth/v2/token'
    ped_api.oauth.authorization_url:    '%api_server_host%/oauth/v2/authorize'
    ped_api.infos.url:                  '%api_server_host%/api/user'

services:
    PaneeDesign\ApiBundle\Handler\ItemHandler:
        arguments: ["@doctrine.orm.entity_manager", "@form.factory"]

    PaneeDesign\ApiBundle\Handler\RestApiHandler:
        arguments:
            $handler: '@PaneeDesign\ApiBundle\Handler\ItemHandler'

    ped_api.api_key_grant:
        class: "%ped_api.api_key_grant.class%"
        arguments: ["@doctrine.orm.entity_manager", "%ped_api.oauth2_user_entity.class%"]
        tags:
            - { name: fos_oauth_server.grant_extension, uri: '%ped_api.oauth.grant_url%' }
    ped_api.oauth2_client:
        class: "%ped_api.oauth2_client.class%"
        arguments: ['%ped_api.client.id%', '%ped_api.client.secret%']
    ped_api.client.credentials_client:
        class: "%ped_api.client.class%"
        arguments: ['@ped_api.oauth2_client', '%ped_api.oauth.authorization_url%', '%ped_api.oauth.token_url%', '%ped_api.infos.url%', client_credentials, { client_id: '%ped_api.client.id%', client_secret: '%ped_api.client.secret%' }]
    ped_api.client.authorize_client:
        class: "%ped_api.client.class%"
        arguments: ['@ped_api.oauth2_client', '%ped_api.oauth.authorization_url%', '%ped_api.oauth.token_url%', '%ped_api.infos.url%', authorization_code, { redirect_uri: '%ped_api.infos.url%' }]
    ped_api.access_token_manager.default:
        class: "%ped_api.access_token_manager.class%"
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "%fos_oauth_server.model.access_token.class%"]
