parameters:
    ped_api.item_handler.class:         PaneeDesign\ApiBundle\Handler\ItemHandler
    ped_api.access_token_manager.class: PaneeDesign\ApiBundle\Manager\TokenManager
    ped_api.client.class:               PaneeDesign\ApiBundle\OAuth2\Client
    ped_api.api_key_grant.class:        PaneeDesign\ApiBundle\OAuth2\ApiKeyGrantExtension
    ped_api.oauth2_user_entity.class:   PaneeDesign\UserBundle\Entity\User
    ped_api.oauth2_client.class:        OAuth2\Client

services:
    ped_api.item_handler:
        class: "%ped_api.item_handler.class%"
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@form.factory"]
        public: true
    ped_api.api_key_grant:
        class: "%ped_api.api_key_grant.class%"
        arguments: ["@doctrine.orm.entity_manager", "%ped_api.oauth2_user_entity.class%"]
        tags:
            - { name: fos_oauth_server.grant_extension, uri: '%api_grant_url%' }
    ped_api.oauth2_client:
        class: "%ped_api.oauth2_client.class%"
        arguments: ['%api_client_id%', '%api_client_secret%']
    ped_api.client.credentials_client:
        class: "%ped_api.client.class%"
        arguments: ['@ped_api.oauth2_client', '%api_authorization_url%', '%api_access_token_url%', '%api_infos_url%', client_credentials, { client_id: '%api_client_id%', client_secret: '%api_client_secret%' }]
    ped_api.client.authorize_client:
        class: "%ped_api.client.class%"
        arguments: ['@ped_api.oauth2_client', '%api_authorization_url%', '%api_access_token_url%', '%api_infos_url%', authorization_code, { redirect_uri: '%api_infos_url%' }]
    ped_api.access_token_manager.default:
        class: "%ped_api.access_token_manager.class%"
        arguments: ["@service_container", "@doctrine.orm.entity_manager", "%fos_oauth_server.model.access_token.class%"]