nelmio_api_doc:
    documentation:
        info:
            title:            Pane&Design API documentation
            description:      API of Pane&Design
            version:          1.0.0
    exclude_sections:         []
    default_sections_opened:  true
    motd:
        template:             'NelmioApiDocBundle::Components/motd.html.twig'
    request_listener:
        enabled:              true
        parameter:            _doc
    sandbox:
        enabled:              true
        endpoint:             null
        accept_type:          null
        body_format: ~
        request_format: ~
        authentication:
            delivery:         query # Required
            name:             access_token # Required
            type:             bearer
        entity_to_choice:     true
    cache:
        enabled:              false
        file:                 '%kernel.cache_dir%/api-doc.cache'
