nelmio_api_doc:
    documentation:
        info:
            title:            Pane&Design API documentation
            description:      API of Pane&Design
            version:          1.0.0
        areas:
            default:
                path_patterns: [ ^/api ]
        securityDefinitions:
            api_key:
                type: apiKey
                in: header
                name: Authorization
                description: "The token you got on login action: Bearer TOKEN"
            #access_token:
            #   type: oauth2
            #   in: header
            #   name: Authorization
            #   description: The token you got on login action
            #   flow: implicit
        security:
            - api_key: []
            #- access_token: []